version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:stable  # Use an appropriate CircleCI Docker image

    steps:
      - checkout
      
      - run:
          name: Checkout secondary repository
          command: |
            git clone git@github.com:rajat3204/jenkins-install-docker.git /tmp/secondary-repo
            cp /tmp/secondary-repo/Dockerfile .
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy

