version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.8  # Use an appropriate CircleCI Docker image

    steps:
      - checkout

      - run:
          name: Checkout secondary repository
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone git@github.com:rajat3204/jenkins-install-docker.git /tmp/secondary-repo
            cp /tmp/secondary-repo/Dockerfile .
            cat Dockerfile

      - setup_remote_docker:
          version: 20.10.7


      - run:
          name: Build Docker image
          command: docker build -t rajat3204/jenkins .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy

